### ISSUE TITLE
Static Code Analysis

### ISSUE THREAD

**Issue by Bugman-creator** [shadow/shadow#1032]
This is for a class project. A Static Code Analysis Tool was run on your project and filtered to only include correct findings
Please find attached the file containing the errors. This file includes the error type, as well as the files and lines where the errors occur

[shadowSCAResults.txt](https://github.com/shadow/shadow/files/5578637/shadowSCAResults.txt)

**Comment by jtracey** [comment]
So static analysis can be a useful tool, but it's important not to treat it like a black box, and to investigate the results it gives before assuming it's operating correctly. I've looked though all the potential NPEs reported, and each one is intentional or a false positive (in all but three cases for the same reason: expanding the [VDL_LOG_ASSERT](https://github.com/shadow/shadow/blob/92e420b76987aad780a9246f8a4d8b159552817e/src/external/elf-loader/vdl-log.h#L50) macro, which needs to trigger the coredump because a failed assertion in the dynamic linker/loader means we can't rely on any correct program behavior, even from libc).

PS: I didn't look into the two memory leaks, since they're in programs that run for a fraction of a second, and will be removed from the next Shadow release anyway.

**Comment by jtracey** [comment]
This issue can be closed, since elf-loader has been removed.
