### ISSUE TITLE
Move topology parsing and processing from igraph to Rust

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#1365]
Shadow currently parses the topology in C using igraph. This topology [will soon be](https://github.com/shadow/shadow/issues/778) in GML format.

We can parse the GML format in Rust using a parser written with [nom](https://github.com/Geal/nom). The parsed GML can be converted into a [petgraph](https://github.com/petgraph/petgraph) graph.

We can compare the memory usage and time it takes to load graphs with igraph and petgraph by using `src/test/legacy/loadgraph.c` for comparison.

**Comment by robgjansen** [comment]
We can close #798 as obsolete once we remove the igraph dependency.

**Comment by robgjansen** [comment]
We talked about changing the logic for how to assign hosts to network graph nodes. I think we settled on the following to start with:
- every host in the shadow config file *must* specify the id of the network node to which the host should be attached
- every host in the shadow config file *may* optionally specify an `ip_address` that shadow will assign to the host, the ip address must be unique among those hosts from the config file that have specified an ip address
- we want to continue supporting the `count` option to run multiple hosts of the same kind; however, if `count > 1` is used, then `ip_address` *must not* be specified (because we must ensure that each host has a unique ip address)
- shadow will no longer support the existing hints: `country_code_hint`, `city_code_hint`, `ip_address_hint` will be removed and instead we will do the host-to-node assignment logic inside of tornettools instead of in shadow.

We considered this rule, but decided *not* to include it because it just adds a special case to the graph handling that would be easier not to have to remember:
- each node in the network graph *must* have a self-loop edge that specifies the network characteristics (i.e. latency) between hosts assigned to the same network node

**Comment by sporksmith** [comment]
> each node in the network graph must have a self-loop edge that specifies the network characteristics (i.e. latency) between hosts assigned to the same network node

How do we handle intra-node connections if there is no such edge?

**Comment by stevenengler** [comment]
> > each node in the network graph must have a self-loop edge that specifies the network characteristics (i.e. latency) between hosts assigned to the same network node
> 
> How do we handle intra-node connections if there is no such edge?

We decided to keep the behaviour consistent with all other nodes and use the shortest path to calculate latency, which will be the latency to the nearest adjacent node and back.

**Comment by stevenengler** [comment]
I'm not clear on how we want to assign IP addresses to hosts. There are 4 different scenarios:

1) Neither the host nor node provide an IP address.
2) The host provides an IP address, but not the node.
3) The node provides an IP address, but not the host.
4) Both the host and node provide different IP addresses.

Should we have the graph specify a subnet for each node rather than a single IP address? The 4 different scenarios would be:

1) Neither the host nor node provide an IP address/subnet. --- Give the node a random, unused /24 subnet, and assign the host an IP in that subnet.
2) The host provides an IP address, but the node does not provide an IP subnet. --- Assign the node the /24 subnet that includes that IP address.
3) The node provides an IP subnet, but the host does not provide an IP address. --- Assign the host an unused IP in that subnet.
4) The host provides an IP address that is not in the node's subnet. --- Error.

We could simplify this by requiring every graph node to include a subnet.

**Comment by robgjansen** [comment]
We are thinking:
- each network graph node _must_ have a subnet

Given that, we have these decision points:
- the host does not specify an ip address -> we assign the host the lowest available ip in the subnet
- the host in a subnet specifies an ip inside the subnet -> all good (as long as the ip is unique)
- the host in a subnet specifies an ip outside of the subnet -> open question -> allow or error???

**Comment by robgjansen** [comment]
After talking through this again:

- network graph nodes do NOT have a subnet.
- hosts in the shadow config MUST specify a network node id to which we will attach it.
- hosts MAY specify an IP address, as long as that IP address is unique among all hosts in the config (otherwise it's an error)
- if a host does not have an IP address, we give it one that is unique among all hosts in a way that is internally specified (this method is not guaranteed to be stable, but probably will be)

Shadow uses graph node `latency` and `packet_loss` attributes for routing packets.

For bandwidth:

- in graph, name them `host_bandwidth_{up,down}`, they are optional in the graph
- when parsing hosts, host must have `bandwidth_{up,down}` OR if not, the network node for the host must have `host_bandwidth_{up,down}` otherwise it's an error.

**Comment by stevenengler** [comment]
This was completed in #.

> We can compare the memory usage and time it takes to load graphs with igraph and petgraph by using src/test/legacy/loadgraph.c for comparison.

I didn't do this, but the new version should generally have better performance for the types of graphs that we use. We now compute the shortest paths before starting the simulation rather than computing them during the simulation as needed. This means our startup cost is higher, but allows us to have a much simpler implementation and we don't require locks on the lookup table / cache during the simulation. We also now compute the shortest paths in parallel using rayon, and unload/free the graph before starting the simulation. This new rust implementation may have larger memory usage for graphs with many nodes and few edges, but this is the opposite of most network graphs.
