### ISSUE TITLE
Support fcntl `F_DUPFD_CLOEXEC`

### ISSUE THREAD

**Issue by kbleeke** [shadow/shadow#1648]
Hello!

**Describe the issue**
fcntl `F_DUPFD` and `F_DUPFD_CLOEXEC` are not supported (for Epoll FDs) and cause a failure with `EINVAL` when creating a [tokio](https://github.com/tokio-rs/tokio) runtime.

**To Reproduce**
Create a Rust Project using Tokio and attempt to build a Runtime like:
```rust
let runtime = tokio::runtime::Builder::new_multi_thread().enable_all().build().expect("build runtime");
```
This code panics with an `std::io::Error` containing `EINVAL`.

**Operating System (please complete the following information):**
Fedora 34
 - Kernel version: post the output of `uname -a`  
```
Linux wrex 5.13.15-200.fc34.x86_64 #1 SMP Wed Sep 8 15:51:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Shadow (please complete the following information):**
```
** Starting Shadow v2.0.0-pre.4-198-gae248676-dirty 2021-09-14--14:21:38 with GLib v2.68.4
```

**Additional context**
In similar fashion to #1637 I'm trying to run a consensus protocol in shadow. This (currently released) project uses the [tokio](https://github.com/tokio-rs/tokio) library for network IO. Unfortunately Tokio tries to immediately duplicate it's Epoll FD when the Runtime is created, causing creation to fail with `EINVAL`.

I was able to hack my was past this by simply returning the same FD for the `F_DUPFD_CLOEXEC` fcntl. This makes the project seem run fine (with the patch from #1637). 

I am wondering what it would take to properly implement FD duplication (Epoll would be enough for me). From looking at the Code it seems like this would be a larger undertaking because the Epoll "Instance" and the FD live in the same object. At least I can't see an obvious way to have two FDs refer to the same Epoll.

**Comment by stevenengler** [comment]
> I am wondering what it would take to properly implement FD duplication (Epoll would be enough for me). From looking at the Code it seems like this would be a larger undertaking because the Epoll "Instance" and the FD live in the same object. At least I can't see an obvious way to have two FDs refer to the same Epoll.

Shadow currently has two ways of simulating descriptors. The first is the ["legacy descriptor"](https://github.com/shadow/shadow/blob/ff671ffdf038597334ae467c56fe774c40b7864a/src/main/host/descriptor/descriptor_types.h#L48-L60) which is written in C and is used for most descriptor/file types (sockets, epoll, files, etc). With this type, the epoll file / posix description and its descriptor live in the same object. The second way of simulating descriptors is in rust, where we have a [PosixFile object](https://github.com/shadow/shadow/blob/ff671ffdf038597334ae467c56fe774c40b7864a/src/main/host/descriptor/mod.rs#L214-L2160) that can be referenced by many [descriptor objects](https://github.com/shadow/shadow/blob/ff671ffdf038597334ae467c56fe774c40b7864a/src/main/host/descriptor/mod.rs#L360-L369). This allows us to easily implement [`dup()`](https://github.com/shadow/shadow/blob/ff671ffdf038597334ae467c56fe774c40b7864a/src/main/host/syscall/unistd.rs#L56-L90) for descriptors implemented with this new code. We currently have pipes implemented with this new rust code, and they support duplication.

Our plan is to move existing legacy descriptors over to this new descriptor / posix file type, but unfortunately the epoll descriptor might need to be last because of how the event system works. Once we move it over we'll essentially get dup support for free, but this won't be in the near-future.

**Comment by stevenengler** [comment]
We now support `F_DUPFD_CLOEXEC` for rust descriptors, but not yet for legacy descriptors like epoll.

**Comment by sporksmith** [comment]
As suspected, this is also a problem for arti, though it can be worked around by building with async-std instead of tokio (`cargo build --no-default-features --features async-std`)
