### ISSUE TITLE
[ERROR] Non-zero return code 2 from make

### ISSUE THREAD

**Issue by N3S3** [shadow/shadow#1973]
**Describe the issue**
[ 55%] Built target shadow-c
make: *** [Makefile:160: all] Error 2
2022-03-17 12:02:20,342 [ERROR] Non-zero return code 2 from make.

**To Reproduce**
sudo ./setup build --clean --test
and
sudo ./setup install

**Operating System (please complete the following information):**
 - OS and version: post the output of `lsb_release -d`  
[Parrot OS Linux release 4.11.3]
 - Kernel version: post the output of `uname -a`  
[Linux parrot 5.14.0-9parrot1-amd64 #1 SMP Debian 5.14.9-9parrot1 (2021-10-26) x86_64 GNU/Linux]

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
[command not found]
 - Which plug-ins you are using:  
[]

**Additional context**
could not find Cargo.toml too

**Comment by robgjansen** [comment]
Is there a reason you are using `sudo`? Shadow does not require root privileges and we strongly advise against using `sudo` because it is an unnecessary security risk and often leads to permissions and environment/path inconsistencies. Please try a fresh install without `sudo`.

Also, I'm not familiar with Parrot, but [here is a list of our officially tested and supported OSes](https://shadow.github.io/docs/guide/supported_platforms.html). Perhaps it's close enough to one of these that it ought to work?

**Comment by stevenengler** [comment]
Closing since there's not enough information to debug further and it's technically not a supported platform. Parrot OS seems to be based on Debian, so it seems like it shouldn't be too hard to get working. If anyone comes across this in the future, then we can re-open.
