### ISSUE TITLE
Pull request actions run on merge result instead of PR head

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2166]
This can result in confusing errors in the case that all of

* The PR merges cleanly
* The action (tests) fails
* The corresponding tests pass on the PR head

This has been rare, but is very confusing when it happens. See https://github.com/shadow/shadow/pull/2147#issuecomment-1129404865

**Comment by sporksmith** [comment]
One solution, proposed by @stevenengler , is to have our checkout actions explicitly check out `github.event.pull_request.head.sha`.

Another possibility is to use the [pull_request_target](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event instead of the [pull_request](github.event.pull_request.head.sha) event. The latter has some security warnings that I don't fully comprehend at the moment.

Before doing either we should be sure that GH won't let us merge a PR where the actions pass on the PR head, but the PR head is out of date with the main branch, meaning we don't actually know whether they'd pass on the merge result.

It looks like this is an option for protected  branches: [Require branches to be up to date before merging](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule). I think we do have this enabled in this repo, but we should verify before making one of the above changes.

**Comment by sporksmith** [comment]
I tried changing `pull_request` to `pull_request_target`, but now the actions aren't running at all.

I checked the settings for my fork of shadow, on which the branch is based. I have "Allow all actions and reusable workflows" checked, so I'm not sure what's happening there...

**Comment by stevenengler** [comment]
> Another possibility is to use the pull_request_target event instead of the pull_request event. The latter has some security warnings that I don't fully comprehend at the moment.

I don't think we should take this approach. The `pull_request_target` runs the PR code in the context of the shadow repository (shadow/shadow) rather than the context of the PR author's repository (ex: stevenengler/shadow). This means that anyone can run arbitrary code in the context of the shadow repository, including accessing secrets for the shadow repository or shadow organization, has full read/write permissions by default, and can access and poison the shadow repository's [cache](https://github.com/actions/cache). The `pull_request_target` is designed to only be used for workflows that have no dependence on user-supplied code (the workflow doesn't run any code from the repository, including bash scripts). 

> I tried changing `pull_request` to `pull_request_target`, but now the actions aren't running at all.

I'm pretty sure that it runs the workflow from the shadow repository, but will checkout the code from the user's repository. Since the shadow repository doesn't have this `pull_request_target` workflow, there is no workflow to run.

**Comment by stevenengler** [comment]
> I'm pretty sure that it runs the workflow from the shadow repository, but will checkout the code from the user's repository. Since the shadow repository doesn't have this `pull_request_target` workflow, there is no workflow to run.

Actually I think this is incorrct. It will run the workflow and checkout the code from the shadow repository. Nothing will be used from the user's repository. I was confused by the [labeler action](https://github.com/actions/labeler) which applies PR labels depending on changed files in the PR. This labeler action actually [checks out](https://github.com/actions/labeler/blob/ed55e8ab1fa323b4a53afb55132c065aa7a9f8f4/src/labeler.ts#L28) the user-supplied code itself and finds changes.
