### ISSUE TITLE
Determinism test is sometimes failing

### ISSUE THREAD

**Issue by sporksmith** [shadow/shadow#2466]
Saw this failure in a PR's CI run, but fairly confident the PR wouldn't have caused it: https://github.com/shadow/shadow/actions/runs/3238878172/jobs/5307594292

I downloaded the data-dirs and found the diff output:

```
$ diff determinism1*-shadow.data/hosts/testnode1/testnode1.test-determinism.1000.strace 
6c6
< 00:00:01.000 [tid 1000] open(<pointer>, O_LARGEFILE | O_RDONLY, 0x7fffffffe866 <invalid>) = 3
---
> 00:00:01.000 [tid 1000] open(<pointer>, O_LARGEFILE | O_RDONLY, 0x7fffffffe856 <invalid>) = 3
```

I think we only recently added the parameter logging for `open`, so this may have been around for a while before.

**Comment by stevenengler** [comment]
I noticed before that `open()` syscalls sometimes have these invalid modes, but I'm not sure why. My guess is that we're again using broken shim libc wrappers. In this case, the shorter version of `open`, which is `open(const char *pathname, int flags)`, should be setting a mode of 0 before making the syscall, but since we override libc's `open` call, that never happens and our shadow syscall handler is reading the mode from uninitialized memory.

**Comment by sporksmith** [comment]
Thanks - I'll take a look
