### ISSUE TITLE
segfault in HoistGlobals.cpp, _plugin_ctors not injected correctly

### ISSUE THREAD

**Issue by vladie** [shadow/shadow#253]
in following code:

```
class HoistGlobalsPass: public ModulePass {
....
        bool runOnModule(Module &M) {
               Function *initFunc = M.getFunction("_plugin_ctors");
               Function::BasicBlockListType &blocks = initFunc->getBasicBlockList();
...  
```

i receive segfault, because no _plugin_ctors function exist (what is it?) and M.getFunction returns NULL. 
what is _plugin_ctors ?

**Comment by robgjansen** [comment]
ctors have something to do with C++ code. You can just wrap the code following initFunc in an if, and skip it if NULL:

```
bool runOnModule(Module &M) {
               Function *initFunc = M.getFunction("_plugin_ctors");
               if(initFunc != NULL) {
                   Function::BasicBlockListType &blocks = initFunc->getBasicBlockList();
                   ...
               }
}
```

Can you test this and let me know if it works? Thanks!

**Comment by vladie** [comment]
yes, it works
thanks

**Comment by vladie** [comment]
no, i was wrong. it doesn't segfaults, but hoisting doesn't works.

**Comment by vladie** [comment]
i've found reason. it is mandatory to include in plugin's source code empty function _plugin_ctors and call it in __shadow_plugin_init__ in order to all constructors being called.

**Comment by robgjansen** [comment]
OK, so I guess `Function *initFunc` should _never_ be NULL? So then why is `M.getFunction("_plugin_ctors");` returning NULL in your case? Do you have a fix?

**Comment by vladie** [comment]
yes, please read my previous answer.

**Comment by robgjansen** [comment]
You have a good workaround.

I believe the real answer is that the code in `HoistGlobals.cpp` is correct in that it tries to inject a call to the ctors functions inside of `__shadow_plugin_init`, since the call is necessary for proper initialization. However, we should still handle the case where `_plugin_ctors` does not exist, since in your case it does not for some reason which we do not understand. If I can figure out how to reproduce the error, I can look into it further.

Would you be willing to share a minimal example plug-in that has the NULL pointer segfault problem?

**Comment by vladie** [comment]
example - is echo plugin from shadow-plugin-extras repository. my experiment code based on it.
it's strange - but i didn't see _plugin_ctors in any of shadow plugin examples. HoistGlobals doesn't create this function from scratch, but searches for already existed symbol in code.
