### ISSUE TITLE
Specify valgrind parameters with "-x" switch

### ISSUE THREAD

**Issue by Skinnor** [shadow/shadow#271]
Currently, if you use the "-x" switch with Shadow, valgrind is executed with parameters fixed in Shadow's source code. It would be nice to be able to specify own parameters with the "-x" switch, for example to use different valgrind tools. At the moment Shadow needs to be rebuild to do that.

**Comment by robgjansen** [comment]
Sounds useful indeed. I hard-coded my favorite settings because I didn't think anyone else would ever care much to run valgrind, but you have invalidated my assumption :) I would welcome a pull request here. My hard-coded settings could remain the default if no parameter to `-x` is specified, and otherwise the user input is used.
