### ISSUE TITLE
etcd example is broken

### ISSUE THREAD

**Issue by stevenengler** [shadow/shadow#2858]
This test is currently commented-out since it doesn't run correctly.

A bisect shows that this appears to have broken with commit 70a3ecf1d47. With this commit and later versions, some seeds work (ex: 222) and others don't (ex: 1). This is possibly related to #2693.

```
error #0: client: endpoint http://127.0.0.1:4001 exceeded header timeout
error #1: client: endpoint http://127.0.0.1:2379 exceeded header timeout
```

**Comment by robgjansen** [comment]
Just making a note that the test may be failing due to a nonzero packet loss rate, and we plan to investigate.

**Comment by stevenengler** [comment]
> Just making a note that the test may be failing due to a nonzero packet loss rate, and we plan to investigate.

I just tried setting a zero packet loss rate, as well as lowering the latency to 1 ms and increasing the bandwidth to 2000 mbps, and the simulation still fails.

**Comment by stevenengler** [comment]
If you enable `model_unblocked_syscall_latency` it seems to "fix" that issue, but fails occasionally (non-deterministicly using the same seed each time) in a different way (probably due to #2693).

**Comment by stevenengler** [comment]
I've found that the issue is caused by having each etcd peer start at the exact same time. As long as the processes are started at times with an offset of at least one nanosecond, the simulation is successful. If the processes start at the same time, then the consensus algorithm is never able to reach quorum.

My guess is that the consensus voting is based on random values generated from a seed, and the seed is based on the current time. So if they are all voting based on the same seed, they won't come to an agreement.

**Comment by stevenengler** [comment]
The etcd server sets the seed using the current time:

https://github.com/etcd-io/etcd/blob/a9c1c217a2d96917c605c0838ffcf79cf48a2783/server/etcdserver/server.go#L123

```go
func init() {
    rand.Seed(time.Now().UnixNano())
    [...]
}
```

**Comment by sporksmith** [comment]
Nice find! Arguably the code under test (here etcd) ought to be using a true entropy source for this seed instead of just the time, but I wouldn't be surprised if this were a footgun that ends up showing up again.

I was thinking it already had in tgen, but looking back it actually wasn't getting seeded at all https://github.com/shadow/tgen/pull/29/files

I don't think there's a nice way to "automatically" avoid it from shadow's perspective. e.g. an even worse version of this behavior would be `srand(time())` in C, which is only second-granularity, so automatically adding a sub-second difference between start times wouldn't help.

I guess we can at least add an etcd note in the application compatibility notes https://shadow.github.io/docs/guide/compatibility_notes.html

**Comment by stevenengler** [comment]
> Nice find! Arguably the code under test (here etcd) ought to be using a true entropy source for this seed instead of just the time, but I wouldn't be surprised if this were a footgun that ends up showing up again.

Yeah, I might post an issue for etcd and see if they'll use something like crypto/rand to seed it, but they might not want to worry about supporting such a niche use-case.

**Comment by stevenengler** [comment]
We have a workaround in shadow (#2880), and it was also fixed in newer versions of etcd (https://github.com/etcd-io/raft/issues/48).
