### ISSUE TITLE
When I run the tor-mininal-yaml,it show the bug like it.

### ISSUE THREAD

**Issue by zhuxiuzhen** [shadow/shadow#3019]
```
We allocated and deallocated the same number of objects :)
00:00:13.725025 [23571:shadow] n/a [INFO] [n/a] [controller.rs:66] [shadow_rs::core::controller] Finished simulation
00:00:13.725330 [23571:shadow] n/a [ERROR] [n/a] [main.rs:397] [shadow_rs::core::main::export] Failed to run the simulation
00:00:13.725421 [23571:shadow] n/a [ERROR] [n/a] [main.rs:397] [shadow_rs::core::main::export] 
00:00:13.725587 [23571:shadow] n/a [ERROR] [n/a] [main.rs:397] [shadow_rs::core::main::export] Caused by:
00:00:13.725685 [23571:shadow] n/a [ERROR] [n/a] [main.rs:397] [shadow_rs::core::main::export]     14 managed processes in unexpected final state
** Shadow did not complete successfully: Failed to run the simulation
**   14 managed processes in unexpected final state
** See the log for details
```

**Comment by zhuxiuzhen** [comment]
I'm thinking whether the version between shadow and tor is incorrect

**Comment by stevenengler** [comment]
Can you run `tor --version`, and also post here the contents of the file `build/src/test/tor/minimal/shadow.data/hosts/relay1/tor.1000.stdout` after running the tor-minimal example?

**Comment by zhuxiuzhen** [comment]
the contents are those:
Jan 01 00:01:00.000 [notice] Tor 0.4.8.1-alpha-dev (git-d4f4fb6088cee8e5) running on shadowsys with Libevent 2.1.11-stable, OpenSSL 1.1.1f, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.31 as libc.
Jan 01 00:01:00.000 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jan 01 00:01:00.000 [notice] This version is not a stable Tor release. Expect more bugs than usual.
Jan 01 00:01:00.000 [warn] Unable to open configuration file "/home/zxz/桌面/shadow/src/test/tor/minimal/shadow.data/hosts/relay1/torrc".
Jan 01 00:01:00.000 [err] Reading config failed--see warnings above.

**Comment by zhuxiuzhen** [comment]
I can run the tor~

**Comment by stevenengler** [comment]
The simulation is failing due to this line:

```
Jan 01 00:01:00.000 [warn] Unable to open configuration file "/home/zxz/桌面/shadow/src/test/tor/minimal/shadow.data/hosts/relay1/torrc".
```

Your tor version 0.4.8.1-alpha-dev is a development version and isn't a version we test with, but it doesn't look like tor has recently changed their code that opens the config file, so I don't think it's a bug in this alpha version of tor.

I'm not sure why tor can't open the torrc file. The `--template-directory shadow.data.template` in `src/test/tor/minimal/run.sh` (or in the cmake test args if you're using the cmake test) should tell Shadow to copy the `shadow.data.template` directory (including `src/test/tor/minimal/shadow.data.template/hosts/relay1/torrc`) to `shadow.data`. So the torrc file should exist there. I can't think of a reason why it wouldn't be.

Are you using the `src/test/tor/minimal//run.sh` script? And if not, are you using the `--template-directory shadow.data.template` option?

**Comment by zhuxiuzhen** [comment]
I run the run.sh  it shows that:
Failed to load configuration file run.sh

Caused by:
    0: Could not parse configuration file
    1: invalid type: string "/root/.local/bin/shadow --template-directory shadow.data.template tor-minimal.yaml > shadow.log", expected struct ConfigFileOptions

**Comment by zhuxiuzhen** [comment]
I've run it successful!!!  thanks!!!

**Comment by stevenengler** [comment]
Glad to hear you got it working!

**Comment by zhuxiuzhen** [comment]
In the shadow, how to see the source code of encryption and decryption of Onion routing protocol. I want to change it for my experiments
