### ISSUE TITLE
I want to change the way of encryption and decryption of Onion routing protocol for my experiments.

### ISSUE THREAD

**Issue by zhuxiuzhen** [shadow/shadow#3020]
I want to change the way of encryption and decryption of Onion routing protocol for my experiments. How can I change the code of it.

**Comment by stevenengler** [comment]
The onion routing implementation exits in [tor](https://gitlab.torproject.org/tpo/core/tor). You'll need to make changes to the tor source code, build it, and use your custom tor version in Shadow. Since the Shadow GitHub issues/discussions are meant just for Shadow, we won't be able to help you with modifying the tor source code here.

**Comment by robgjansen** [comment]
Please ask on the Tor project communication channels if you need help with making changes to Tor.
