### ISSUE TITLE
Log file size problem

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#3224]
The shadow log file size has increased significantly and is causing us to run out of actions storage.

The file size increased from about 0.5 MB per Tor benchmark to 110 MB per Tor benchmark starting with this weekly:
https://github.com/shadow/benchmark/actions/runs/6752723049

The most recent PR merged after the above is #3213.

@stevenengler any ideas?

**Comment by stevenengler** [comment]
There seems to be millions of "mmap on fd X for Y bytes failed" warnings. I think this happens because the PR added a new check to make sure it wasn't a special file, and it turns out that tor does try to mmap one of these special files.

https://github.com/shadow/shadow/blob/83934cebca5801cec9e5b93ca601da59aaa7fe9d/src/main/host/syscall/handler/mman.rs#L268-L273

This causes a warning further up in the calling code.

https://github.com/shadow/shadow/blob/83934cebca5801cec9e5b93ca601da59aaa7fe9d/src/main/host/syscall/handler/mman.rs#L210-L218

I think I'll make this second warn log a debug log instead.

**Comment by stevenengler** [comment]
On my local machine, I only see these warnings for the "fileserver" host. On the benchmark runner, I see it for all tor hosts ("4uthority2", "relay33exitguard", "relay227exit", etc).

At least on my machine, the processes are trying to mmap an fd for "/etc/localtime".

```
00:00:01.000000000 [tid 1000] open("/etc/localtime", (empty), Mode(0x0)) = 3
00:00:01.000000000 [tid 1000] fstat() = 0
00:00:01.000000000 [tid 1000] mmap(0x0, 118, PROT_READ, MAP_PRIVATE, 3, 0) = 0xfffffffffffffff3 ((unknown errno 13))
```
