### ISSUE TITLE
Route path calculation issue

### ISSUE THREAD

**Issue by archon159** [shadow/shadow#674]
Hello,

I am Sean, a new user of Shadow.
I found some issues in src/main/routing/shd-topology.c 

1. Shadow does not accept the topology with incomplete graph.
- Shadow returns FALSE for an indirect graph.
- Normally, there could be hosts which are not connected directly, but it seems that Shadow does not consider such case.

2. Shadow prefers direct path as default.
- The variable prefersDirectPaths is set TRUE as default. (I could not found how to configure this in configuration file, and there is not any comment about this in user guide.)
- Although I changed prefersDirectPath to False, Shadow calls lookupDirectPath in _topology_getPathEntry if the graph is complete. (The graph is always complete due to the first issue.)
- In _topology_storePathInCache, it does not calculate any non-direct paths if there is a direct path between two hosts. (A direct path always exists due to above issues.)
- Thus, Shadow anyway selects the direct path between hosts even if there is a shorter non-direct path.

3. Shadow returns false in assert though we avoided above issues.
- utility_assert(vertexIndexPointer != NULL) in _topology_computeSourcePaths (line 1690) makes the problem.
- It seems that vertexIndexPointer is popped from a queue "attachedTargets" which contains pointers converted by a macro GINT_TO_POINTER(vertexIndex).  If vertexIndex is 0, the pointer also becomes 0, which makes an exception from the assert function.

Thanks,
Sean

**Comment by robgjansen** [comment]
Thanks for reporting these issues. I won't be able to work through these until next week at the earliest. For now, could you please clarify the following:

  - Which version of Shadow are you using? Please post the output of `shadow --version`

  - For your 1., do you mean *complete*, *directed*, or *connected*? These each have different meanings.

  - Shadow does require that the graph have a single connected component so that it can route packets to any host that is added anywhere in the network. However, I believe that Shadow should work with both directed and undirected graphs, and with both complete or incomplete graphs. Please post the simplest possible counterexample topology to help us debug.

Thank you!

**Comment by archon159** [comment]
1) The result of shadow --version : 
Shadow v1.13.0-11-g1190a34-dirty 2018-08-03 (built 2018-12-06) running GLib v2.48.2 and IGraph v0.7.1

2) This issue is about undirected graphs, and the meaning of complete graph was the graph whose nodes are connected to each other.

3)
![figure2](https://user-images.githubusercontent.com/24450840/52034030-75862f00-256a-11e9-8cac-e44f592a2714.png)

**Comment by robgjansen** [comment]
I think I understand what you mean, but you are still being loose with your terminology. It is important to be precise because otherwise I don't understand which scenarios are problematic.

A _connected_ graph is one in which any node can reach any other node through any number of edges. So if we have a graph A-B-C-D, this is a connected graph because A can reach D through B and C.

A _complete_ graph is one in which every node can reach every other node through a **single** edge. Each node is one hop away from each other node.

(See also https://en.wikipedia.org/wiki/Connectivity_(graph_theory))

You claimed that Shadow does not accept a topology with an _incomplete_ graph. You also claimed that Shadow returns FALSE for an _undirected_ graph. I think both of these claims are FALSE, here is a working counter-example showing an undirected and incomplete graph:

```
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="packetloss" attr.type="double" for="edge" id="d9" />
  <key attr.name="jitter" attr.type="double" for="edge" id="d8" />
  <key attr.name="latency" attr.type="double" for="edge" id="d7" />
  <key attr.name="type" attr.type="string" for="node" id="d5" />
  <key attr.name="bandwidthup" attr.type="int" for="node" id="d4" />
  <key attr.name="bandwidthdown" attr.type="int" for="node" id="d3" />
  <key attr.name="countrycode" attr.type="string" for="node" id="d2" />
  <key attr.name="ip" attr.type="string" for="node" id="d1" />
  <key attr.name="packetloss" attr.type="double" for="node" id="d0" />
  <graph edgedefault="undirected">
    <node id="poi-1">
      <data key="d0">0.0</data>
      <data key="d1">0.0.0.0</data>
      <data key="d2">US</data>
      <data key="d3">17038</data>
      <data key="d4">2251</data>
      <data key="d5">net</data>
    </node>
    <node id="poi-2">
      <data key="d0">0.0</data>
      <data key="d1">0.0.0.1</data>
      <data key="d2">US</data>
      <data key="d3">17038</data>
      <data key="d4">2251</data>
      <data key="d5">net</data>
    </node>
    <node id="poi-3">
      <data key="d0">0.0</data>
      <data key="d1">0.0.0.2</data>
      <data key="d2">US</data>
      <data key="d3">17038</data>
      <data key="d4">2251</data>
      <data key="d5">net</data>
    </node>
    <edge source="poi-1" target="poi-2">
      <data key="d7">50.0</data>
      <data key="d8">0.0</data>
      <data key="d9">0.0</data>
    </edge>
    <edge source="poi-2" target="poi-3">
      <data key="d7">50.0</data>
      <data key="d8">0.0</data>
      <data key="d9">0.0</data>
    </edge>
  </graph>
</graphml>
```

This works correctly for me in Shadow.

**Comment by robgjansen** [comment]
I'm still looking into the `prefersDirectPaths` setting, and it might be the case that Shadow is mishandling the case that you posted in your previous image.

**Comment by robgjansen** [comment]
You can configure the `preferdirectpaths` graph attribute in the topology xml file. Here is an example:

```
<?xml version="1.0" encoding="utf-8"?><graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="preferdirectpaths" attr.type="string" for="graph" id="d0" />
  <graph edgedefault="undirected">
    <data key="d0">True</data>
    <node id="2.235.244.95">
   ...
```

You can see here that the `graph` attribute is named `preferdirectpaths`, and that it is set to `True` immediately following the declaration of the graph element.

This comment in the code explains the indented behavior of this configuration:

```
    /* Also a graph property. Normally when a graph is not complete, Shadow
     * will always do shortest path to get from A to B, even if a path from A
     * to B already exists. Sometimes ACB is shorter than AB.
     *
     * If this is true and the graph is not complete, then when Shadow needs to
     * route from A to B, it will prefer to use AB (if it exists) even if it
     * could do shortest path to determine ACB is shorter. */
    gboolean prefersDirectPaths;
```

If this value is not set (the default is `FALSE`), then Shadow *should* default to doing a shortest path lookup on the graph.

```
    /* if the value is not set in the graph, we default to always using shortest path */
    gboolean prefersDirectPaths = FALSE;
```

So in the case that you gave, Shadow _should_ be doing a shortest path lookup to find the 2 millisecond path instead of using the single 50 millisecond edge.

Do you have a copy of the XML topology file that I could test?

**Comment by archon159** [comment]
1. 
Unfortunately, I do not have such xml files that were used for testing.
I've just tested your given xml setting, and it worked.
I will notify you with xml setting file when such case occurs again.
Thanks for your checking.

2.
I remember that there was another problem even when prefersDirectPaths was set to FALSE.
(Already explained in initial comment)
Is it also works correctly with your setting?

Thanks,
Sean.

**Comment by robgjansen** [comment]
Please re-open if you are still experiencing issues with the intended behavior of the `preferdirectpaths` option.
