### ISSUE TITLE
Unable to run shadow on Ubuntu 18.04 (docker)

### ISSUE THREAD

**Issue by Samdney** [shadow/shadow#676]
I set up a docker image following the wiki instructions, based on Ubuntu 18.04. When I try to run shadow I get the following error:

`user@docker-shadow:~$` .shadow/bin/shadow --help
/home/user/shadow/src/external/elf-loader/vdl-map.c:740, file_map_do, Unable to perform remapping
Segmentation fault (core dumped)

**Comment by robgjansen** [comment]
The docker instructions were created for an old version of Shadow (v1.10.2). If you installed the latest version of Shadow, you'll need to follow the setup instructions here:
https://github.com/shadow/shadow/wiki/1.1-Shadow#apt-debianubuntu

Most notably, you'll need to install the `libc-dbg` package.

Did you install the packages as shown in the link above?

**Comment by Samdney** [comment]
Yes I used this instructions of the mentioned link, including the installation of  `libc-dbg`

**Comment by jtracey** [comment]
I haven't tested this because I don't have docker installed right now, but: I've seen before issues with Docker arising because /dev/shm is very small (e.g., Firefox runs into this if you're not careful). We rely on /dev/shm mappings for saving memory usage in normal builds, but it's not strictly necessary, and can be disabled by building with the debug (`-g`) option enabled. If that works, and you want these memory savings for some larger experiments, you could try manually specifying the size of Docker's /dev/shm instead.

**Comment by robgjansen** [comment]
@Samdney were you able to get things running in docker?

**Comment by robgjansen** [comment]
Please re-open if you are still experiencing this issue.

**Comment by robgjansen** [comment]
For future reference, from [the docs](https://github.com/shadow/shadow/blob/v1.15.0/docs/1.1-Shadow.md#dependencies):

If you are installing Shadow within a Docker container, you must increase the size of the container's /dev/shm mount and make it executable by passing `--tmpfs /dev/shm:rw,nosuid,nodev,exec,size=1g` (with a suitable size for your system and experiments) to docker run.
