### ISSUE TITLE
Use hash instead of RNG for hintless hosts

### ISSUE THREAD

**Issue by jtracey** [shadow/shadow#690]
If a host in a shadow experiment specifies hints that no nodes in the network topology satisfy, Shadow will supply a random IP. Relevant code here:
https://github.com/shadow/shadow/blob/a31f3e2125afd4e4048e218916fb05749c09713b/src/main/routing/shd-topology.c#L2305

This fine (I assume), but makes things slightly difficult for the case where we're trying to reconstruct largely-identical networks on other experimentation platforms: since we don't use the same pseudo-RNG that Shadow uses internally, there's no simple way of predicting those random values. Would it be acceptable to switch the RNG in this case to some standard hash of the name of the host, to make it the same value on both platforms?

(Note: this is very low priority, the intermediary fix is just "make sure the experiment supplies only satisfiable hints")

**Comment by robgjansen** [comment]
My take is that, when reconstructing networks, we shouldn't rely on the internal assignment of hintless hosts to topology vertex, hash or RNG or otherwise. Doing so is fragile because this assignment method could potentially change at some point in the future. As you mention, we already have a way to configure hosts to be attached to the same vertex, so we can just use that.

Also, note that Shadow does log where it attaches each host in the topology, so this information could be used to mirror an experiment. Here is an example from a shadow log file:

```
00:00:05.204113 [thread-0] n/a [message] [n/a] [shd-topology.c:2412] [topology_attach] attached address '216.58.218.238' to vertex 64 ('poi-48') with attributes (ip=190.111.118.234, citycode=(null), countrycode=AR, geocode=(null), type=cluster) using hints (ip=216.58.218.238, citycode=(null), countrycode=(null), geocode=US, type=server)
```

Notice that the host IP address and the IP address of the topology vertex where it was attached are both given.

**Comment by sporksmith** [comment]
Should Shadow crash then if there's an unsatisfiable hint?

**Comment by robgjansen** [comment]
Shadow now requires hosts to be placed on specific network node ids (see #1573), which pushes the assignment logic to higher level tools but also allows users to manually adjust network node assignments in the config file rather than guessing at what Shadow will do. I think that obsoletes this issue.
