### ISSUE TITLE
epoll-writeable-shadow test case takes too long

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#756]
There must be some kind of failure occuring in the `epoll-writeable-shadow` test since it is taking longer than 1 minute to complete:

https://github.com/shadow/shadow/runs/571228243#step:8:208

**Comment by florian-vuillemot** [comment]
Maybe the problem comes from the topology config? If you change `<kill time="10000"/>` by for example `<kill time="1000"/>` the execution time is divided by 10.

```
1/3 Test #1: epoll ............................   Passed    1.10 sec
    Start 2: epoll-shadow
2/3 Test #2: epoll-shadow .....................   Passed    0.11 sec
    Start 3: epoll-writeable-shadow
3/3 Test #3: epoll-writeable-shadow ...........   Passed    6.57 sec
100% tests passed, 0 tests failed out of 3
Total Test time (real) =   7.85 sec
```

And less for `<kill time="100"/>`
```
1/3 Test #1: epoll ............................   Passed    1.10 sec
    Start 2: epoll-shadow
2/3 Test #2: epoll-shadow .....................   Passed    0.10 sec
    Start 3: epoll-writeable-shadow
3/3 Test #3: epoll-writeable-shadow ...........   Passed    0.80 sec
100% tests passed, 0 tests failed out of 3
Total Test time (real) =   2.07 sec
```

I tried to remove the for loop in the client (for(;;)) in shd-test-epoll-writeable.c, but I encountered the same time error. As if Shadow continues to work even if the 2 nodes are finished.
Is it normal ?

**Comment by sporksmith** [comment]
`git bisect` identifies the culprit as https://github.com/shadow/shadow/commit/58224fd5187e4a603567639fd3bd6fedff0ed1fb, using the test script:

```
#!/bin/bash
./setup build --clean --test -j8
cd build
timeout 5 ctest -R epoll-writeable-shadow`
```

**Comment by sporksmith** [comment]
@florian-vuillemot Yeah, the issue seems to be shadow no longer deciding to exit earlier; in the commit before 58224fd it exits quickly; at and after 58224fd shadow keeps running until it hits that timeout. I poked a bit to add more debugging output from the test itself and do more error-checking; the test-code all seems to be WAI. I even changed the client to exit after the expected amount of data was received, and shadow keeps running long after both client and server have exited:

```
3: 00:00:00.265732 [thread-0] 00:00:11.068000001 [message] [testnode~11.0.0.1] [shd-process.c:953] [_process_logReturnCode] main success code '0' for process 'testnode.test_epoll_writeable.1000'
...
3: 00:00:00.495681 [thread-0] 00:00:11.270000001 [message] [client~11.0.0.2] [shd-process.c:953] [_process_logReturnCode] main success code '0' for process 'client.test_epoll_writeable.1000'
...
```

Some network simulation bits seem to keep working for a bit after both have exited:

```
3: 00:00:00.495923 [thread-0] 00:00:11.272000000 [message] [testnode~11.0.0.1] [shd-packet.c:642] [packet_addDeliveryStatus] [SND_TCP_DEQUEUE_RETRANSMIT] packetID=1:1086 11.0.0.1:22222 -> 11.0.0.2:48466 seq=1086 ack=1 sack=NA window=121 bytes=1434 header=ACK tsval=11171000000 tsechoreply=0 status=SND_CREATED,SND_TCP_ENQUEUE_THROTTLED,SND_SOCKET_BUFFERED,SND_TCP_ENQUEUE_RETRANSMIT,SND_INTERFACE_SENT,INET_SENT,SND_TCP_DEQUEUE_RETRANSMIT
3: 00:00:00.495932 [thread-0] 00:00:11.272000000 [message] [testnode~11.0.0.1] [shd-packet.c:642] [packet_addDeliveryStatus] [PDS_DESTROYED] packetID=1:1086 11.0.0.1:22222 -> 11.0.0.2:48466 seq=1086 ack=1 sack=NA window=121 bytes=1434 header=ACK tsval=11171000000 tsechoreply=0 status=SND_CREATED,SND_TCP_ENQUEUE_THROTTLED,SND_SOCKET_BUFFERED,SND_TCP_ENQUEUE_RETRANSMIT,SND_INTERFACE_SENT,INET_SENT,SND_TCP_DEQUEUE_RETRANSMIT,PDS_DESTROYED
... (lots more similar)
```

That also finished up pretty quickly though, and then it's just heartbeat messages until it gets killed by the timeout. With heartbeats filtered out:

```
...
3: 00:00:00.511681 [thread-0] 00:00:12.068000001 [debug] [testnode~11.0.0.1] [shd-timer.c:219] [_timer_expire] timer fd 1 expired; isClosed=0 expireID=0 minValidExpireID=523281500
3: 00:01:07.745090 [thread-0] n/a [message] [n/a] [shd-scheduler.c:92] [_scheduler_stopHosts] starting to shut down 2 hosts
...
```

Full test output:
[log.txt.gz](https://github.com/shadow/shadow/files/4463722/log.txt.gz)

**Comment by florian-vuillemot** [comment]
I searched long time in several commits but I didn't find anything... But I ended up founding something and I would like to have you opinion on it.

We are in single thread policy (SP_SERIAL_GLOBAL), and the worker is run through slave_run function. And if I understand correctly, this function stays blocked in the loop on scheduler_pop that calls _schedulerpolicyglobalsingle_pop. This function runs events. And if I understand correctly I receive events till the end of the program. Do you think I should look deeper into it ?

**Comment by sporksmith** [comment]
@robgjansen - [here's](https://github.com/sporksmith/shadow/commit/75c1965f0efb27303c003244a7ac40fe3e8d424d) the extra checking and early exit I added locally.

@florian-vuillemot - After chatting with Rob today my understanding is that the *only* normal exit criteria is getting to the end of the simulation time, but normally after all processes have exited no more events get generated, so the scheduler can just jump to the end. This issue is low-ish priority, and I'm handing off to Rob to maybe look at in a week or so. If you're motivated to dig further in the meantime I'm sure we'd appreciate the contribution :)

**Comment by florian-vuillemot** [comment]
Yes of course, I will search. It looks like a good issue to better understand the simulator. I will come back to you to obtain more context on elements that I might not understand.
Keep in touch.

**Comment by florian-vuillemot** [comment]
Do you think that the problem can come from worker_isAlive in the worker  ? I think we can't just check if the worker exist, we also have to check if the process is running. I added this test in the function but I obtained a lot of races conditions.. And I think adding mutex is not the best way.
What do you think ?

**Comment by robgjansen** [comment]
The reason for this bug occurred to me when looking at #766.

We moved to a "token bucket" network interface model in 58224fd5187e4a603567639fd3bd6fedff0ed1fb, where every refill time interval (e.g. 1 millisecond) we add a task to the scheduler to refill the token bucket 1 millisecond from now. So even if all processes finish and no one is sending packets, we still have to continuously execute those refill tasks until the simulation end time. In other words, we are unable to benefit from "jumping" to the end of the simulation.

The fix I have in mind involves changing the refill algorithm:

1. if we try to refill a bucket that is already full, we go into "hibernate" mode and do not schedule a refill task;
1. whenever some tokens are removed, if the bucket is in hibernate mode, we leave hibernate mode and we schedule a refill task.

This should fix the long running test bug, and also make the simulation generally more efficient. I'll throw together a branch later tonight that will likely make #766 obsolete (though it was helpful for me to realize what the problem is, so thank you @florian-vuillemot!)

**Comment by armadev** [comment]
Tor had the same issues with bucket refill costs, though we might have an extra problem because looping through every connection for every refill period is super expensive for relays with many connections.

The design we seem to have settled upon is to notice when a new time unit has rolled over (e.g. per millisecond), and if so, back-refill all the tokens for all the time units since we last did a refill.

That way if there are periods of inactivity, we don't spin refilling the buckets a little bit at a time. Or said another way, if nothing will use any tokens for 8ms, nobody will notice if you fill it a little bit 8 times, or fill it more, once, right before using it.

I guess which approach is more useful for Shadow depends a lot on what underlying behavior Shadow will be simulating -- e.g.. what sort of gaps in network behavior it has.
