### ISSUE TITLE
elf-loader tests run twice

### ISSUE THREAD

**Issue by jtracey** [shadow/shadow#791]
**Describe the issue**
When running `./setup test`, elf-loader tests first run as their own set of tests, then get run again when running the Shadow tests. Previously, they only ran once, as their own set of tests. This makes testing take ~4 seconds longer on my machine, which, now that #756 is resolved, is a non-trivial fraction of test time. A git bisect shows this started at 2154dfa19d0d2d2e8e4f290186758193fbf0ba47.

**To Reproduce**
`./setup build -cgt -j 4 && ./setup install && ./setup test`

**Operating System (please complete the following information):**
Ubuntu 19.10

**Shadow (please complete the following information):**
 - Version: post the output of `shadow --version`  
`Shadow v1.13.2-587-g6ee31a4a 2020-05-04 (built 2020-05-07) running GLib v2.62.4 and IGraph v0.7.1`

**Additional context**
As long as elf-loader is part of Shadow, I'd recommend any testing setup run those tests first, since they're a lot more precise than the Shadow tests and are guaranteed to cause issues over all.

**Comment by sporksmith** [comment]
Thanks for pointing this out!

The bug was introduced because I moved the `enable_testing` call in the root `CMakeLists.txt` to happen before recursing into subdirectories. This was to support unit-tests that live next to the code they're testing, and so ends up capturing the elf-loader tests as well. They then end up running twice because the `setup` script's test command still explicitly runs the elf-loader tests, even though the elf-loader tests are also run as part of the "everything else" tests.

Naively, we could just modify the setup script to no longer explicitly call the elf-loader tests. You raise a good point though that if a unit test (e.g. elf-loader test) fails, it's likely to cause secondary failures in the integration tests, which for the most part would just be noise. It might be reasonable to run the unit tests first and then not bother with integration tests if the unit tests fail.

I'll send a fix PR shortly.

**Comment by sporksmith** [comment]
Unfortunately I don't see a good way to tell ctest to run just the unit tests or just the integration tests. I was thinking maybe we could pass a flag to ctest to run in build/src but exclude build/src/test/* in the first run, and then run ctest again in build/src/test. I don't see any flag to filter by path though, only by label. Hypothetically we could mandate that unit tests and/or integration tests have some label identifying them as such (e.g. "unit-" or "integration-" label prefixes), but that seems fragile.

If we do want to be able to run the unit tests separately, the right way would probably be to move `src/test` so that it's not under the `src` subtree. e.g. we could have a separate root subdirectory `test`.

I'm not sure it's worth it though; for now I'm going to propose just running all of the tests together, and we can revisit if it becomes a practical issue.

**Comment by sporksmith** [comment]
BTW, if you want to run specific tests for code you're actively working on, you can always run ctest directly.

e.g. (running in a subshell to preserve the workding directory):
```
(cd build/src/external/elf-loader && ctest -j8)
```

or:
```
(cd build && ctest -N -R elfloader -j8)
```
