### ISSUE TITLE
Enable docker CI testing for CentOS 8

### ISSUE THREAD

**Issue by robgjansen** [shadow/shadow#818]
Setup our CI configuration to run the Shadow integration tests in a CentOS 8 docker instance.

**Comment by stevenengler** [comment]
@robgjansen @sporksmith CentOS (7 and 8) doesn't include the igraph package. This is simple enough to build/install from source, but adds about 6 minutes to the CI test time. In addition, CentOS 8 also needs to build the procps-ng-devel package from source (another ~2 minutes).

We have a few options:

1. Build these directly within the GitHub job. This will require rebuilding these dependencies four times (to include {debug,!debug} and {gcc,clang}) for each platform each time we run the tests and will add significant time to testing.
2. Build some rpms manually, host them somewhere, and download them during the CI tests.
3. Create our own testing-only docker images hosted on Dockerhub. Since these will be for CI testing only, we will not need to maintain these images (for example by applying security patches). Maybe rebuild them every 6 months or so with the latest updates. In this case, we would need to decide whether to generate a docker image for each platform (for simplicity), or only for the ones that need dependencies to be built from source with the remaining platforms being configured within the CI workflow. An advantage of using a custom docker image for each platform is that it should reduce the testing time by allowing us to skip the package manager download/install step while running tests.

My order of preference is 3, 2, 1. Anyone have any thoughts about this?

**Comment by sporksmith** [comment]
I've been toying with the idea of 3 anyway (maintaining our own testing images) since, as you mentioned, installing dependencies is already a big chunk of the test time.

Do you have a plan for how we might maintain those docker images? We probably want the Dockerfiles in version control somewhere. Could we keep them in the Shadow repo itself, and maybe use a separate GH workflow to build and deploy new images when they change?

**Comment by stevenengler** [comment]
That's a good idea about building/deploying them automatically. It seems we can configure Docker Hub to automatically build images when we push to a repository, or we can do this within a GitHub workflow instead (this is probably the better option so we keep everything in one place). I'll look into exactly how this might work. We will need someone, probably @robgjansen, to make a Docker Hub account for Shadow to store the images.

I have no preference for keeping the Dockerfiles in the shadow repo or another repo. If we put them in the shadow repo, where do we want them? In something like `src/test/docker`, or somewhere else?

**Comment by sporksmith** [comment]
Keeping them in the same repo sgtm until if and when we have a reason to break them out into another repo.

I'm not sure keeping them under `src/test` is ideal, since they could be useful outside of tests too.

Maybe a top-level directory `docker/`?

But yeah, let's let @robgjansen weigh in

**Comment by robgjansen** [comment]
Wait, on CentOS you need to install the `EPEL` repo first, many many "standard" packages are available there. I know igraph is there, and probably procps-ng-devel too.

https://fedoraproject.org/wiki/EPEL

If possible, we should totally not increase our maintenance workload by creating our own docker images.

**Comment by robgjansen** [comment]
There are a bunch of other CentOS package repos too. I doubt we need anything other than EPEL, but here is the link if you are interested:
https://wiki.centos.org/AdditionalResources/Repositories

**Comment by stevenengler** [comment]
Thanks, I thought these were the same as the "CentOS Extras" repository so I didn't add them. So igraph is on the EPEL repo for CentOS 7, but the EPEL repo has neither [igraph](https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/i/) nor [procps-ng-devel](https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/p/) for CentOS 8. I spent some time looking through the additional repositories for procps-devel, but didn't find any. I also don't see any listed for CentOS 8 on https://pkgs.org/search/?q=igraph.

**Comment by robgjansen** [comment]
> but the EPEL repo has neither igraph nor procps-ng-devel for CentOS 8

You may be able to install the latest rpm from CentOS 7 or maybe one of the recent Fedora rpms? Usually those work.

**Comment by stevenengler** [comment]
> You may be able to install the latest rpm from CentOS 7 or maybe one of the recent Fedora rpms? Usually those work.

Alright I installed them from the CentOS 7 repos and they seem to work (other than a procps-ng bug that gets carried over from CentOS 7, which I already have a fix for). I guess that's good enough for testing purposes.
