### ISSUE TITLE
Error in documentation for building custom libc.

### ISSUE THREAD

**Issue by rwails** [shadow/shadow#950]
**Describe the issue**

The documentation currently states:

```
cd ~ && git clone --depth=2 -b interpose-syscalls-2.17-centos7 https://github.com/sporksmith/glibc.git
cd ~/glibc && git diff glibc-2.17-centos7 > ~/rpmbuild/SOURCES/use-syscall-function.patch
```

This doesn't work with the version of git packaged with centos7 -- I think the issue is that we are cloning a single branch, but then git diff is expecting the glibc-2.17-centos7 branch to exist in the repo. Is it too expensive to fetch the entire glibc repo?

**Comment by sporksmith** [comment]
I *think* this would work if we change the depth to 3 (since it'll then include the tip of `glibc-2.17-centos7` again), but that'll break again if another commit gets added to `interpose-syscalls-2.17-centos7`.

It'd be nice if we could tell `git` to clone exactly these two branches and the set of commits between them (`glibc-2.17-centos7..interpose-syscalls-2.17-centos7`), but I don't know offhand if there's such a way.

We could just change the instructions to clone the whole repo, but it is a substantial operation.

**Comment by sporksmith** [comment]
No reason to do this now that preload mode uses seccomp as a fallback. The doc was removed in 0ebab05706762fcdc8d788a25930134e20dfd403
