### ISSUE TITLE
shadow w/ `-n preload` hangs when running `phold` benchmark using custom libc package

### ISSUE THREAD

**Issue by rwails** [shadow/shadow#963]
**Describe the issue**

Shadow plugins get stuck in `shim_ensure_init()` under certain workloads.

**To Reproduce**

Running the phold test in preload mode - commit d05caa

**Backtrace**

![image_from_ios](https://user-images.githubusercontent.com/4669872/92176301-2d955100-ee0c-11ea-83ab-6f17056ef72a.jpg)

**Comment by sporksmith** [comment]
We've only been able to repro IFF using the recompiled libc on centos 7. In that environment, ptrace mode fails as well.

What we see in the backtrace is that the shim logger ends up using the heap inside logger_elapsed_string; because the memorymanager remaps the heap on the first syscall, this isn't safe and can lead to memory corruption. I thought I'd gotten rid of all such heap usage, but apparently `gmtime_r` uses the heap.

After locally fixing that, ptrace-mode works, but in preload-mode the child segfaults, leaving shadow hanging.

It turns out due to the earlier init, we end up initializing the shim inside libpthread's global constructor (which we can also see in the stack trace above). At that time, pthread_self() returns 0, which we end up using as the key to store the ipc blk in the per-thread tree.

On a later syscall after libpthread is initialized, pthread_self() returns non-zero, and so there is no corresponding entry in the per-thread tree.

I'm going to try switching to using a thread-local (`__thread`) variable to store the ipc blk instead of using the tree. I'm not positive that will work either, since thread-local-storage might also be set up by a global constructor.

Alternatively we can go back to initializing at constructor priority 200 (which is guaranteed to let libc's constructors run first). There are some risks there too; e.g.

* libc could conceivably call getpid or gettid syscalls and cache the result, getting the native IDs instead of the shadow IDs and causing the wrong ones to be returned later
* other library's constructors could use the same priority (or even lower, ignoring gcc warnings), allowing them to run uninterposed.

Will report back if switching to __thread works.
